### ISSUE TITLE
Support for extra namespaces

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ec-cli#103]
@callumforrester and I have been discussing additional namespaces.

There are 3 ways this could be supported

- put a value in values.yaml 
  - but this requires that all helm charts apply this to all resources which is not desirable
- add an out of band config file that ec tool reads and applies on the command line
  - this is doable but breaks the model that folders under /services are pure helm charts
- add a command line option to the ec deploy commands
  - this breaks the model that the repo contains all knowledge of the state of the beamline
  - it would also require the namespace parameter adding to all commands like 'attach' and 'ps' (this issue really applies to any mechanism that supports >1 namespace)

Since none of these are that great, we came back to the idea that a single namespace for a beamline makes the best sense. There is no particular isolation required between gda services and IOCs. There is a question of authZ but frankly this is just adding more managment for little benefit.

Leaving this as a ticket for discussion for now. @coretl - any thoughts?

**Comment by gilesknap** [comment]
If we do go with a single namespace, then we'll need to get the cloud team to rename one of the namespaces and delete the other + this does mean redoing the authorization - probably by merging the set of users with access (or just starting again)

**Comment by coretl** [comment]
I vote for merge the namespaces

**Comment by callumforrester** [comment]
I think merging namespaces is a good solution for now, but worth considering how we would support multiple in future if the requirement emerged.

Suggestions for merged namespace name:
- `ixx-services`
- `ixx-svc`
- `ixx-ec`

The third is my current favourite

**Comment by gilesknap** [comment]
`ixx-ec` sound good to me

**Comment by DiamondJoseph** [comment]
Moving the DAQ services will be one less step after [we only need one SealedSecret per-beamline](https://github.com/DiamondLightSource/blueapi/pull/374) (*cough @callumforrester cough*). We haven't finished moving the beamlines over from the last change of namespace though, who is going to request from the cloud team?

**Comment by gilesknap** [comment]
@DiamondJoseph I think we should wait until we know we are ready for this and remove all the old namespaces to avoid compounding the confusion.

**Comment by gilesknap** [comment]
@callumforrester this is the issue that covers the thing you asked about in slack. It would be best in my view to make this a one-off blanket change across all beamline clusters (including bl45p) and delete all of the old namespaces.

**Comment by gilesknap** [comment]
OK we now have shared namespace ixx-beamline on all beamline clusters.

Closing.
