### ISSUE TITLE
Dirty helm repos

### ISSUE THREAD

**Issue by marcelldls** [epics-containers/ec-cli#126]
I have had some strange behavior. Even though I have set the ioc image `image: ghcr.io/epics-containers/ioc-adsimdetector-runtime:2024.4.1` I have an IOC (bl01c-ea-test-04) that fails upon a `deploy-local` with `Back-off pulling image "ghcr.io/epics-containers/ioc-adsimdetector-linux-runtime:2024.2.1"`. This is the wrong image

What I tried:
- Running `./update-helm` 
- `ec delete` and redeploy bl01c-ea-test-04

What actually worked:
- `git reset --hard` and `git clean -dxi`

Investigating why:
- Even though `ioc-instance` is set to `3.4.0`, it seems that the existence of `ioc-instance-3.0.0.tgz` in the service's directory does something strange to the deploy  (This local repo had been used to upgrade IOC instance). This repo is archived and attached. [bl01c.zip](https://github.com/epics-containers/edge-containers-cli/files/14995875/bl01c.zip)

To avoid such unexpected behavior - Is it possible to clean up the helm artifacts after each `deploy-local` (unless in debug?)

**Comment by gilesknap** [comment]
I believe this is a duplicate of #114 and that your git clean removed the *.tgz as I suggest in that issue.

This never happens with deploy as it is always a fresh clone being used. But with deploy-local those pesky tgzs and associated lockfiles are the culprit (I think)

**Comment by marcelldls** [comment]
@gilesknap I believe you are correct. Remembered it being only about `ec template` but it seems to be the same root cause. Closing
