### ISSUE TITLE
Add a beamline monitor TUI

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ec-cli#131]
Now that we are starting to have beamlines with mix of traditional and K8S IOCS, we need a way for scientists to monitor, start and stop the K8S ones as they don't show on the HW status screen and don't have a procServControl screen.

Rather than try to shoehorn something on to the IOC list on HW Status we propose to have a TUI mode for the `ec` command. We could then have a single button on the HW status screen labelled `Kubernetes IOCs` which launches a terminal and executes:
```bash
source environment.sh
ec monitor
```
This would ask for credentials if the user's K8S token has expired or just run if they have a current token. The `ec monitor` command would launch a TUI with these features:

- scroll-able list of all K8S IOCs in the cluster including stopped ones
- status of each IOC shown
- buttons next to the IOC for stop/start/restart/logs
- logs will bring you to a new scroll-able log of both current and previous logs
- exiting logs returns you to monitor mode

This could make a great interim tool for IOC management - could even do the job indefinitely. It is also relatively easy to do as everything needed is already implemented in `ec` and this is just a TUI over the same functionality. No additional credential management etc. required.

I've discussed this with @OCopping  and he is interested in looking into it - assigning to him.
Also mentioned it to Gareth and he was in favour of something like this rather than the existing pure command line tool.

**Comment by OCopping** [comment]
Fixed by #139
