### ISSUE TITLE
Add ec debug command

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ec-cli#136]
For working out why a service is failing when running in the cluster.

This command should:

- delete the current version of the service from the cluster
- deploy the service again with all the usual settings but override the entry point to be 'sleep 600'
- exec a bash shell in the pod once it has launched

This would allow us to then go into the /epics/ioc folder and launch the start.sh multiple times.
But this would also generally work for any service.

IMPORTANT - it is probably best for us to arrange for busybox to be installed in our runtime containers for this purpose. This includes a basic version of vi so we can try out changes to files.

ALSO - this command should have an option to replace the container image with the developer version (and maybe that should be the default - you only want runtime for this if you cannot reproduce the issue in a developer container)

**Comment by gilesknap** [comment]
@coretl for next time :-)

**Comment by coretl** [comment]
...and `sleep 600` should probably be `sleep infinity`, just in case 10 minutes of debugging isn't long enough!

**Comment by marcelldls** [comment]
I believe this is now solved by https://github.com/epics-containers/ec-services-template/pull/29
