### ISSUE TITLE
Implement .config/edge-containers-cli/settings.yaml or similar

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ec-cli#156]
Use this to provide config and tell the CLI which beamline you are currently using.

Probably should also use environment still - but have this set on beamline workstations by default. Require that you pick which beamline you are configuring if you are not on a beamline workstation.

Allows us to drop environment.sh hopefully.

This is an extremely loose spec - but just wanted to capture that we discussed this today.

**Comment by marcelldls** [comment]
Agreed to stick to env variables only to reduce the complexity since changing beamline needs more than just new environment variables
