### ISSUE TITLE
docs are useless

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ec-cli#55]
In this org we have a bunch of documentation pages attached to individual projects with very little in (because they are skeleton based).

But we have quite decent documentation for the org itself.

I propose ditching the docs from epics-containers-cli, ibek and the rest and putting links to the global docs in their readmes.

Thoughts @coretl @GDYendell

**Comment by coretl** [comment]
I like in depth documentation to live with the module in question, so that it's clear that docs need to be updated with new features, but I'm happy for `ibek`, `ec` etc. to not have any tutorials, and they live in the org docs

**Comment by gilesknap** [comment]
OK agreed.

**Comment by gilesknap** [comment]
Resolved. The project is now based on python copier with docs disabled.

**Comment by gilesknap** [comment]
(will be resolved by #96 )
