### ISSUE TITLE
Temp folder gets in the way of debugging

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ec-cli#83]
When you perform a function like

```
ec -v ioc deploy-local iocs/xxxxx
```

It constructs the necessary helm chart in a temporary folder and deploys it.

If there is a problem then the best way to debug is to repeat the commands printed out by the `-v` option.

However, they won't work because the temporary folder is destroyed. It would be much better if either

- the temp folder was retained when an exception occurs
- or an additional debug flag caused the folder to be kept (ec -dv for example)

Perhaps both of the above options make sense.

**Comment by gilesknap** [comment]
@marcelldls I had to stay home today to get the next tutorial finished. 

I promised to help you debug an issue you were having deploying IOCs. Lets do that on Tues. If you have time to look at this issue before then it would help massively with debugging that problem.

**Comment by marcelldls** [comment]
> @marcelldls I had to stay home today to get the next tutorial finished.
> 
> I promised to help you debug an issue you were having deploying IOCs. Lets do that on Tues. If you have time to look at this issue before then it would help massively with debugging that problem.

Are you sure that this is not already implemented? https://github.com/epics-containers/epics-containers-cli/blob/main/src/epics_containers_cli/ioc/helm.py#L51

I tried it and it seems that the ec -dv option already retains the temp folder. If so, maybe it could be more clear with possibly a `log.debug(f"Temporary directory {self.tmp} retained")`?
