### ISSUE TITLE
We need a way to list stopped IOCs

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ec-cli#87]
ec ps -a 

does not work 

ec ioc start  TAB TAB

also does not work

I think fixing both of those is the best way to make stopped IOCs visible.

**Comment by marcelldls** [comment]
It seems to have broken with your changes as it was working yesterday. `ec ioc stop` is also now broken with the new changes. Should the tests not have caught this?

**Comment by marcelldls** [comment]
For my new deployments `ec ioc start TAB TAB` does actually work. However the iocs are not deployed with the tag of the chart update. Also `ec ps -a` does seem to work although I cant test it with a stopped ioc
